<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.kie.j2cl.tools</groupId>
        <artifactId>j2cl-parent</artifactId>
        <version>v20260527-1</version>
    </parent>
    <artifactId>backend-kotlin</artifactId>
    <packaging>pom</packaging>


    <name>J2CL Backend Kotlin</name>
    <description>
        J2CL is a powerful, simple and lightweight transpiler from Java to Closure style JavaScript.
        The project is designed, implemented, and maintained by the J2CL team at Google.
        This distribution is slightly modified from the original and packaged for Maven Central by Vertispan LLC.
        The links and references in this pom.xml will reference the Vertispan fork, to ensure that any error introduced
        by our packaging are not incorrectly blamed on the upstream Google repository.
    </description>
    <url>https://github.com/vertispan/j2cl</url>
    <inceptionYear>2015</inceptionYear>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>J2CL team</name>
            <organization>Google</organization>
            <organizationUrl>https://www.google.com</organizationUrl>
        </developer>
        <developer>
            <name>Colin Alworth</name>
            <email>colin@vertispan.com</email>
            <organization>Vertispan LLC</organization>
            <organizationUrl>https://www.vertispan.com/</organizationUrl>
        </developer>
    </developers>

    <issueManagement>
        <url>https://github.com/vertispan/j2cl/issues</url>
        <system>GitHub Issues</system>
    </issueManagement>

    <scm>
        <connection>scm:git:https://github.com/vertispan/j2cl.git</connection>
        <developerConnection>scm:git:git@github.com:vertispan/j2cl.git</developerConnection>
        <url>https://github.com/vertispan/j2cl</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>

        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>ast</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>backend-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>backend-kotlin-ast</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>backend-kotlin-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>backend-kotlin-objc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>backend-kotlin-source</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
